name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main       # Deploy to production
      - dev        # Deploy to development
      - staging    # Deploy to staging
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - dev
      - staging

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set Environment Variables
        id: set_env
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          if [ "${GITHUB_REF##*/}" == "main" ]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
            echo "AZURE_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" == "dev" ]; then
            echo "DEPLOY_ENV=development" >> $GITHUB_ENV
            echo "AZURE_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" == "staging" ]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
            echo "AZURE_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"              # App source code path
          api_location: ""               # Api source code path (optional)
          output_location: "build"       # Built app content directory (optional)

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          action: "close"
